version: "3.9"

services:
  kafka:
    container_name: kafka_event
    image: confluentinc/cp-kafka:7.7.7
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  postgres:
    container_name: noteon_db
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: notedbv2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - notedb:/var/lib/postgresql/data

  redis:
    container_name: noteon_db_redis
    image: redis:8.4.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - noteon_redis:/data

  ai_service:
    container_name: python_ai
    build:
      context: ../ai-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      GROQ_API_KEY: ${GROQ_API_KEY}

  go_service:
    container_name: go_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./internals/config/noteon_back.json:/app/internals/config/noteon_back.json:ro

    environment:
      APP_ENV: dev

      DB_DEV_URL: postgresql://postgres:postgres@postgres:5432/notedbv2?sslmode=disable
      REDIS_HOST: redis:6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      FIREBASE_URL: internals/config/noteon_back.json
      PORT: ":3000"

volumes:
  notedb:
  noteon_redis:
